import { Inbox, InboxItemType } from "@/types/inboxType";
import { FileType } from "@/types/timelineType";
import { UserRole } from "@/types/userTypes";

export const mockInboxItems: Inbox[] = [
  {
    id: "inbox1",
    fromId: "user1",
    participantId: "participant1",
    userId: "user3",
    projectId: "project1",
    title: "Welcome to the team!",
    description: "We're excited to have you join our development team. Please review the onboarding materials.",
    type: InboxItemType.NOTIFICATION,
    seenAt: "",
    isArchived: true,
    isDeleted: false,
    isStarred: true,
    timestamp: "2025-06-01T10:00:00Z",
    updatedAt: "2025-06-01T11:00:00Z",
    fromUser: {
      id: "user1",
      firstname: "John",
      lastname: "Doe",
      email: "john@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=John%20Doe&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org1",
      isActive: true,
    },
    attachments: [
      {
        id: "file0a",
        name: "onboarding-guide.pdf",
        inboxIs: "inbox1",
        type: FileType.PDF,
        size: 1250000,
      },
    ],
  },
  {
    id: "inbox2",
    fromId: "user2",
    participantId: "participant2",
    userId: "user4",
    projectId: "project2",
    title: "Project deadline update",
    description: "The client has requested to move the project deadline forward by one week.",
    type: InboxItemType.MESSAGE,
    seenAt: "2025-06-02T12:00:00Z",
    isArchived: false,
    isDeleted: true,
    isStarred: false,
    timestamp: "2025-06-02T10:00:00Z",
    updatedAt: "2025-06-02T11:00:00Z",
    fromUser: {
      id: "user2",
      firstname: "Jane",
      lastname: "Smith",
      email: "jane@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Jane%20Smith&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org2",
      isActive: false,
    },
    attachments: [],
  },
  {
    id: "inbox3",
    fromId: "user3",
    participantId: "participant3",
    userId: "user5",
    projectId: "project3",
    title: "Team meeting invitation",
    description: "You're invited to join our weekly team standup meeting every Monday at 9 AM.",
    type: InboxItemType.INVITE,
    seenAt: "2025-06-03T12:00:00Z",
    isArchived: false,
    isDeleted: false,
    isStarred: false,
    timestamp: "2025-06-03T10:00:00Z",
    updatedAt: "2025-06-03T11:00:00Z",
    fromUser: {
      id: "user3",
      firstname: "Alice",
      lastname: "Taylor",
      email: "alice@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Alice%20Taylor&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org3",
      isActive: true,
    },
    attachments: [
      {
        id: "file2a",
        name: "meeting-agenda.docx",
        inboxIs: "inbox3",
        type: FileType.DOCX,
        size: 85000,
      },
    ],
  },
  {
    id: "inbox4",
    fromId: "user4",
    participantId: "participant4",
    userId: "user6",
    projectId: "project1",
    title: "Code review required",
    description: "Please review the latest pull request for the authentication module.",
    type: InboxItemType.TASK,
    seenAt: "",
    isArchived: false,
    isDeleted: false,
    isStarred: true,
    timestamp: "2025-06-04T10:00:00Z",
    updatedAt: "2025-06-04T11:00:00Z",
    fromUser: {
      id: "user4",
      firstname: "Bob",
      lastname: "Brown",
      email: "bob@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Bob%20Brown&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org1",
      isActive: false,
    },
    attachments: [],
  },
  {
    id: "inbox5",
    fromId: "user5",
    participantId: "participant5",
    userId: "user7",
    projectId: "project2",
    title: "Great work on the presentation!",
    description: "Your presentation to the client was excellent. The feedback has been overwhelmingly positive.",
    type: InboxItemType.COMMENT,
    seenAt: "2025-06-05T12:00:00Z",
    isArchived: true,
    isDeleted: true,
    isStarred: false,
    timestamp: "2025-06-05T10:00:00Z",
    updatedAt: "2025-06-05T11:00:00Z",
    fromUser: {
      id: "user5",
      firstname: "Carol",
      lastname: "Lee",
      email: "carol@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Carol%20Lee&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org2",
      isActive: true,
    },
    attachments: [
      {
        id: "file4a",
        name: "client-feedback.pdf",
        inboxIs: "inbox5",
        type: FileType.PDF,
        size: 195000,
      },
    ],
  },
  {
    id: "inbox6",
    fromId: "user6",
    participantId: "participant1",
    userId: "user8",
    projectId: "project3",
    title: "Security audit completed",
    description: "The quarterly security audit has been completed. Please review the findings and recommendations.",
    type: InboxItemType.NOTIFICATION,
    seenAt: "",
    isArchived: false,
    isDeleted: false,
    isStarred: false,
    timestamp: "2025-06-06T10:00:00Z",
    updatedAt: "2025-06-06T11:00:00Z",
    fromUser: {
      id: "user6",
      firstname: "Dan",
      lastname: "White",
      email: "dan@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Dan%20White&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org3",
      isActive: false,
    },
    attachments: [],
  },
  {
    id: "inbox7",
    fromId: "user7",
    participantId: "participant2",
    userId: "user9",
    projectId: "project1",
    title: "Bug report: Login issue",
    description: "Users are reporting intermittent login failures. This needs immediate attention.",
    type: InboxItemType.MESSAGE,
    seenAt: "2025-06-07T12:00:00Z",
    isArchived: false,
    isDeleted: true,
    isStarred: true,
    timestamp: "2025-06-07T10:00:00Z",
    updatedAt: "2025-06-07T11:00:00Z",
    fromUser: {
      id: "user7",
      firstname: "Eve",
      lastname: "Green",
      email: "eve@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Eve%20Green&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org1",
      isActive: true,
    },
    attachments: [
      {
        id: "file6a",
        name: "error-logs.txt",
        inboxIs: "inbox7",
        type: FileType.TXT,
        size: 75000,
      },
    ],
  },
  {
    id: "inbox8",
    fromId: "user8",
    participantId: "participant3",
    userId: "user10",
    projectId: "project2",
    title: "Sprint planning session",
    description: "Join us for the next sprint planning session this Friday at 2 PM.",
    type: InboxItemType.INVITE,
    seenAt: "",
    isArchived: false,
    isDeleted: false,
    isStarred: true,
    timestamp: "2025-06-08T10:00:00Z",
    updatedAt: "2025-06-08T11:00:00Z",
    fromUser: {
      id: "user8",
      firstname: "Frank",
      lastname: "King",
      email: "frank@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Frank%20King&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org2",
      isActive: false,
    },
    attachments: [],
  },
  {
    id: "inbox9",
    fromId: "user9",
    participantId: "participant4",
    userId: "user1",
    projectId: "project3",
    title: "Documentation update needed",
    description: "The API documentation needs to be updated to reflect the recent changes in version 2.1.",
    type: InboxItemType.TASK,
    seenAt: "2025-06-09T12:00:00Z",
    isArchived: false,
    isDeleted: false,
    isStarred: false,
    timestamp: "2025-06-09T10:00:00Z",
    updatedAt: "2025-06-09T11:00:00Z",
    fromUser: {
      id: "user9",
      firstname: "Grace",
      lastname: "Young",
      email: "grace@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Grace%20Young&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org3",
      isActive: true,
    },
    attachments: [
      {
        id: "file8a",
        name: "api-changes.zip",
        inboxIs: "inbox9",
        type: FileType.ZIP,
        size: 423000,
      },
    ],
  },
  {
    id: "inbox10",
    fromId: "user10",
    participantId: "participant5",
    userId: "user2",
    projectId: "project1",
    title: "Excellent debugging skills!",
    description: "Your approach to solving the performance issue was innovative and effective. Well done!",
    type: InboxItemType.COMMENT,
    seenAt: "",
    isArchived: true,
    isDeleted: true,
    isStarred: false,
    timestamp: "2025-06-01T10:00:00Z",
    updatedAt: "2025-06-01T11:00:00Z",
    fromUser: {
      id: "user10",
      firstname: "Hank",
      lastname: "Hill",
      email: "hank@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Hank%20Hill&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org1",
      isActive: false,
    },
    attachments: [],
  },
  {
    id: "inbox11",
    fromId: "user1",
    participantId: "participant1",
    userId: "user3",
    projectId: "project2",
    title: "Server maintenance scheduled",
    description: "Scheduled maintenance window for our production servers this weekend from 2-6 AM.",
    type: InboxItemType.NOTIFICATION,
    seenAt: "2025-06-02T12:00:00Z",
    isArchived: false,
    isDeleted: false,
    isStarred: true,
    timestamp: "2025-06-02T10:00:00Z",
    updatedAt: "2025-06-02T11:00:00Z",
    fromUser: {
      id: "user1",
      firstname: "John",
      lastname: "Doe",
      email: "john@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=John%20Doe&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org1",
      isActive: true,
    },
    attachments: [
      {
        id: "file10a",
        name: "maintenance-schedule.pdf",
        inboxIs: "inbox11",
        type: FileType.PDF,
        size: 156000,
      },
    ],
  },
  {
    id: "inbox12",
    fromId: "user2",
    participantId: "participant2",
    userId: "user4",
    projectId: "project3",
    title: "Client wants to discuss new features",
    description: "The client is interested in adding real-time collaboration features to the platform.",
    type: InboxItemType.MESSAGE,
    seenAt: "",
    isArchived: false,
    isDeleted: true,
    isStarred: false,
    timestamp: "2025-06-03T10:00:00Z",
    updatedAt: "2025-06-03T11:00:00Z",
    fromUser: {
      id: "user2",
      firstname: "Jane",
      lastname: "Smith",
      email: "jane@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Jane%20Smith&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org2",
      isActive: false,
    },
    attachments: [],
  },
  {
    id: "inbox13",
    fromId: "user3",
    participantId: "participant3",
    userId: "user5",
    projectId: "project1",
    title: "Coffee chat invitation",
    description: "Would you like to grab coffee this afternoon to discuss the new project requirements?",
    type: InboxItemType.INVITE,
    seenAt: "2025-06-04T12:00:00Z",
    isArchived: false,
    isDeleted: false,
    isStarred: false,
    timestamp: "2025-06-04T10:00:00Z",
    updatedAt: "2025-06-04T11:00:00Z",
    fromUser: {
      id: "user3",
      firstname: "Alice",
      lastname: "Taylor",
      email: "alice@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Alice%20Taylor&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org3",
      isActive: true,
    },
    attachments: [
      {
        id: "file12a",
        name: "project-requirements.docx",
        inboxIs: "inbox13",
        type: FileType.DOCX,
        size: 234000,
      },
    ],
  },
  {
    id: "inbox14",
    fromId: "user4",
    participantId: "participant4",
    userId: "user6",
    projectId: "project2",
    title: "Performance optimization task",
    description: "Database queries are running slower than expected. Please investigate and optimize.",
    type: InboxItemType.TASK,
    seenAt: "",
    isArchived: false,
    isDeleted: false,
    isStarred: true,
    timestamp: "2025-06-05T10:00:00Z",
    updatedAt: "2025-06-05T11:00:00Z",
    fromUser: {
      id: "user4",
      firstname: "Bob",
      lastname: "Brown",
      email: "bob@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Bob%20Brown&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org1",
      isActive: false,
    },
    attachments: [],
  },
  {
    id: "inbox15",
    fromId: "user5",
    participantId: "participant5",
    userId: "user7",
    projectId: "project3",
    title: "Love the new UI design!",
    description: "The new user interface looks fantastic. The color scheme and layout are much more intuitive.",
    type: InboxItemType.COMMENT,
    seenAt: "2025-06-06T12:00:00Z",
    isArchived: true,
    isDeleted: true,
    isStarred: false,
    timestamp: "2025-06-06T10:00:00Z",
    updatedAt: "2025-06-06T11:00:00Z",
    fromUser: {
      id: "user5",
      firstname: "Carol",
      lastname: "Lee",
      email: "carol@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Carol%20Lee&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org2",
      isActive: true,
    },
    attachments: [
      {
        id: "file14a",
        name: "ui-mockups.zip",
        inboxIs: "inbox15",
        type: FileType.ZIP,
        size: 892000,
      },
    ],
  },
  {
    id: "inbox16",
    fromId: "user6",
    participantId: "participant1",
    userId: "user8",
    projectId: "project1",
    title: "Backup process completed",
    description: "The weekly backup process has been completed successfully. All data is secure.",
    type: InboxItemType.NOTIFICATION,
    seenAt: "",
    isArchived: false,
    isDeleted: false,
    isStarred: false,
    timestamp: "2025-06-07T10:00:00Z",
    updatedAt: "2025-06-07T11:00:00Z",
    fromUser: {
      id: "user6",
      firstname: "Dan",
      lastname: "White",
      email: "dan@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Dan%20White&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org3",
      isActive: false,
    },
    attachments: [],
  },
  {
    id: "inbox17",
    fromId: "user7",
    participantId: "participant2",
    userId: "user9",
    projectId: "project2",
    title: "Urgent: Production issue",
    description: "There's a critical issue affecting user payments. This needs immediate attention.",
    type: InboxItemType.MESSAGE,
    seenAt: "2025-06-08T12:00:00Z",
    isArchived: false,
    isDeleted: true,
    isStarred: true,
    timestamp: "2025-06-08T10:00:00Z",
    updatedAt: "2025-06-08T11:00:00Z",
    fromUser: {
      id: "user7",
      firstname: "Eve",
      lastname: "Green",
      email: "eve@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Eve%20Green&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org1",
      isActive: true,
    },
    attachments: [
      {
        id: "file16a",
        name: "payment-error-logs.txt",
        inboxIs: "inbox17",
        type: FileType.TXT,
        size: 127000,
      },
    ],
  },
  {
    id: "inbox18",
    fromId: "user8",
    participantId: "participant3",
    userId: "user10",
    projectId: "project3",
    title: "Workshop on React best practices",
    description: "Join our workshop next Tuesday to learn about the latest React development patterns.",
    type: InboxItemType.INVITE,
    seenAt: "",
    isArchived: false,
    isDeleted: false,
    isStarred: true,
    timestamp: "2025-06-09T10:00:00Z",
    updatedAt: "2025-06-09T11:00:00Z",
    fromUser: {
      id: "user8",
      firstname: "Frank",
      lastname: "King",
      email: "frank@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Frank%20King&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org2",
      isActive: false,
    },
    attachments: [],
  },
  {
    id: "inbox19",
    fromId: "user9",
    participantId: "participant4",
    userId: "user1",
    projectId: "project1",
    title: "Update user permissions",
    description: "Please update the user permissions for the new team members joining next week.",
    type: InboxItemType.TASK,
    seenAt: "2025-06-01T12:00:00Z",
    isArchived: false,
    isDeleted: false,
    isStarred: false,
    timestamp: "2025-06-01T10:00:00Z",
    updatedAt: "2025-06-01T11:00:00Z",
    fromUser: {
      id: "user9",
      firstname: "Grace",
      lastname: "Young",
      email: "grace@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Grace%20Young&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org3",
      isActive: true,
    },
    attachments: [
      {
        id: "file18a",
        name: "team-member-list.pdf",
        inboxIs: "inbox19",
        type: FileType.PDF,
        size: 67000,
      },
    ],
  },
  {
    id: "inbox20",
    fromId: "user10",
    participantId: "participant5",
    userId: "user2",
    projectId: "project2",
    title: "Your code is clean and well-documented!",
    description: "I reviewed your latest commits and I'm impressed by the code quality and documentation.",
    type: InboxItemType.COMMENT,
    seenAt: "",
    isArchived: true,
    isDeleted: true,
    isStarred: false,
    timestamp: "2025-06-02T10:00:00Z",
    updatedAt: "2025-06-02T11:00:00Z",
    fromUser: {
      id: "user10",
      firstname: "Hank",
      lastname: "Hill",
      email: "hank@example.com",
      role: UserRole.USER,
      profilePicture: "https://api.dicebear.com/7.x/initials/svg?seed=Hank%20Hill&backgroundColor=d1d5db&fontFamily=Arial&fontSize=36&chars=2",
      organizationId: "org1",
      isActive: false,
    },
    attachments: [],
  },
];