ALTER TABLE "activities" ALTER COLUMN "project_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "activities" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "participants" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "participants" ALTER COLUMN "project_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "code" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "code" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "name" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "domain" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "domain" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "description" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "description" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "max_team_size" SET DEFAULT 5;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "max_team_size" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "site_link" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "site_link" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "repository_link" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "repository_link" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "visibility" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "deadline" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "duration_in_days" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "tech_stack" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "tech_stack" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "location" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "location" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "time_lines" ALTER COLUMN "project_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "time_lines" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "time_lines" ALTER COLUMN "remarks" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT '2025-06-28T04:40:22.922Z';--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT '2025-06-28T04:40:22.923Z';--> statement-breakpoint
ALTER TABLE "participants" ADD CONSTRAINT "participants_user_id_project_id_pk" PRIMARY KEY("user_id","project_id");